---
version: "3.7"
x-common-airflow_variables: &airflow_variables
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__TEST_CONNECTION=Enabled

services:
  airflow:
    container_name: airflow
    build: airflow
    ports:
      - "8080:8080"
    command: ["standalone"]
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    environment: *airflow_variables
  minio:
    container_name: minio
    build: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
