warehouse:
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/warehouse/dbt.duckdb
      filesystems:
        - fs: s3
          anon: false
          key: "admin"
          secret: "admin1234"
          client_kwargs:
            endpoint_url: "http://minio:9000"
  target: dev
