warehouse:
  outputs:
    dev:
      type: duckdb
      path: /home/airflow/dbt.duckdb
      filesystems:
        - fs: s3
          anon: false
          key: "admin"
          secret: "admin1234"
          client_kwargs:
            endpoint_url: "http://minio:9000"
      external_root: "s3://warehouse/dbt"
      threads: 4
  target: dev
