---
warehouse:
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      threads: 4
      filesystems:
        - fs: s3
          anon: false
          key: "admin"
          secret: "admin1234"
          client_kwargs:
            endpoint_url: "http://minio:9000"
  target: dev
